### ISSUE TITLE
SPIRES: extend author-count search to support <,>

### ISSUE THREAD

**Issue by kaplun** [inveniosoftware/invenio-query-parser#29]
From inveniosoftware/invenio#873:

When searching by author-count (or find ac), < and > should be supported, as they are with dates.

**Comment by Panos512** [comment]
I believe this is a search problem and not a parser one since the parsing produces the same result as it does for dates.

Example:
find d > 2012 parses to:  SpiresOp(Keyword('d'), GreaterOp(Value('12')))
and
find ac > 3 parses to:  SpiresOp(Keyword('ac'), GreaterOp(Value('3')))

Anyway elasticsearch should treat this correctly since the output is ok.
